/* ============== CURRICULUM DATA (pure — no app-state dependencies) ============== */

/* ============== CURRICULUM DATA ============== */

export const SUBJECTS = {
  polity: { label:"Polity — Laxmikanth", color:"#C9A227", topics:[
    "Historical Background of the Constitution, Making of the Constitution, Salient Features",
    "Preamble, Union & its Territory, Citizenship",
    "Fundamental Rights",
    "Directive Principles of State Policy, Fundamental Duties",
    "Amendment of the Constitution, Basic Structure Doctrine",
    "Parliamentary System, Federal System",
    "Centre-State Relations, Inter-State Relations",
    "Emergency Provisions",
    "President, Vice-President",
    "Prime Minister, Central Council of Ministers, Cabinet Committees",
    "Parliament — Lok Sabha, Rajya Sabha, Parliamentary Committees",
    "Supreme Court, Judicial Review, Judicial Activism",
    "Governor, State Executive (CM & Council of Ministers), State Legislature, High Court",
    "Local Government — Panchayati Raj & Municipalities, Union Territories, Special Provisions for States",
    "Constitutional Bodies (Election Commission, UPSC/SPSC, Finance Commission, CAG, AG) & Non-Constitutional Bodies (NITI Aayog, CVC, CBI, Lokpal/Lokayukta)",
    "Political Parties, Pressure Groups, Electoral Reforms, Recent Amendments — full revision"
  ]},
  geography: { label:"Geography — NCERT + GC Leong", color:"#4FA893", topics:[
    "NCERT Class 6 — Geography basics, the Globe, Motions of the Earth",
    "NCERT Class 6 (contd.) — Interior of the Earth, Rocks, Landforms",
    "NCERT Class 7 — Environment, Climate, Natural Vegetation & Wildlife",
    "NCERT Class 9 — India: Physical Features, Drainage Systems",
    "NCERT Class 9 — India: Climate, Natural Vegetation, Wildlife",
    "NCERT Class 9/10 — Population, Economic Geography basics",
    "NCERT Class 11 — Geomorphology (Earth's interior, landforms)",
    "NCERT Class 11 — Climatology (atmosphere, insolation, pressure & winds)",
    "NCERT Class 11 — Oceanography (currents, tides, temperature/salinity) & Biogeography",
    "NCERT Class 11 — India: Physiography, Drainage, Climate, Soils, Vegetation",
    "GC Leong — Weather elements: atmosphere structure, insolation, temperature, pressure belts, winds",
    "GC Leong — Humidity, precipitation, air masses, fronts, cyclones, world climate types (Koppen)",
    "GC Leong — Landforms: weathering, geomorphic processes, river/karst/glacial/arid landforms",
    "GC Leong — Oceans (relief, temperature, salinity, movements), Natural vegetation & soils",
    "Economic Geography basics (NCERT Class 12) + Map-work practice + Full revision"
  ]},
  economy: { label:"Economy — Vivek Singh", color:"#7C9CBF", topics:[
    "Basics of Economy, National Income Accounting (GDP, GNP, NNP, NDP)",
    "Economic Growth & Development, Planning in India (Five Year Plans, NITI Aayog)",
    "Money & Banking — RBI functions, Monetary Policy",
    "Banking system — Commercial banks, Financial Inclusion, NBFCs",
    "Inflation — types, causes, measures, WPI/CPI",
    "Public Finance — Budget, Fiscal Policy, Deficits, FRBM Act",
    "Taxation — Direct/Indirect Taxes, GST",
    "External Sector — Balance of Payments, Foreign Trade, Exchange Rate",
    "Agriculture — Cropping pattern, Green Revolution, MSP, Agricultural Marketing (APMC, e-NAM)",
    "Agriculture (contd.) — Food Security, PDS, Land Reforms, Subsidies",
    "Industry & Infrastructure — Industrial Policy, MSMEs, Infrastructure sectors",
    "Industry (contd.) — Industrial Licensing, Disinvestment, PSUs",
    "Services Sector, Employment & Unemployment, Poverty & Inequality",
    "International Economic Organizations (WTO, IMF, World Bank), Economic Reforms of 1991, Sustainable Development",
    "Capital Market (SEBI, stock markets), Insurance sector, Miscellaneous topics — full revision"
  ]},
  modernHistory: { label:"Modern History — Spectrum", color:"#B5654A", topics:[
    "Advent of Europeans, Carnatic Wars, Expansion of British Power in Bengal (Plassey, Buxar)",
    "British Expansion — Mysore Wars, Anglo-Maratha Wars, Anglo-Sikh Wars",
    "Administrative Structure — Company rule, Regulating Act to Charter Acts, Governor-Generals",
    "Economic Impact of British Rule — Land Revenue Systems (Permanent, Ryotwari, Mahalwari), De-industrialization, Drain of Wealth",
    "Socio-Religious Reform Movements (Brahmo Samaj, Arya Samaj, and others)",
    "Revolt of 1857 — causes, nature, consequences",
    "Post-1857 Policies, Administrative Changes, Indian Councils Acts",
    "Rise of Indian Nationalism — Formation of INC, Moderates Phase",
    "Extremist Phase, Partition of Bengal, Swadeshi Movement",
    "Revolutionary Activities, Home Rule Movement, Lucknow Pact",
    "Gandhi's Arrival — Champaran, Kheda, Ahmedabad; Rowlatt Act; Jallianwala Bagh",
    "Non-Cooperation Movement, Khilafat Movement, Simon Commission",
    "Civil Disobedience Movement, Round Table Conferences, Communal Award, Poona Pact",
    "Government of India Act 1935, Congress Ministries, Quit India Movement, INA & Subhas Bose",
    "Post-War Developments — Cabinet Mission, Direct Action Day, Mountbatten Plan, Independence & Partition",
    "Growth of Communalism, Left Movements, Peasant & Working-Class Movements, Integration of Princely States",
    "Eminent Personalities, important Committees/Acts summary — full revision"
  ]},
  ancientHistory: { label:"Ancient History", color:"#8C6E4A", topics:[
    "Pre-historic period, Indus Valley Civilization",
    "Vedic Age — Early & Later Vedic period",
    "Religious Movements — Jainism, Buddhism",
    "Mauryan Empire",
    "Post-Mauryan period (Shungas, Kushans, Satavahanas), Sangam Age",
    "Gupta Empire, Post-Gupta period (Harshavardhana)",
    "South Indian Kingdoms — Pallavas, Chalukyas, Cholas",
    "Art, Architecture & Literature of Ancient India — full revision"
  ]},
  medievalHistory: { label:"Medieval History", color:"#6E5A8C", topics:[
    "Early Medieval India, Rajputs, Arab & Turkish Invasions",
    "Delhi Sultanate — Slave, Khilji, Tughlaq dynasties",
    "Delhi Sultanate — Sayyid, Lodi dynasties, Administration",
    "Vijayanagara & Bahmani Kingdoms",
    "Mughal Empire — Babur to Akbar",
    "Mughal Empire — Jahangir to Aurangzeb, Decline of the Mughals",
    "Bhakti & Sufi Movements, Regional Kingdoms (Marathas, Sikhs)",
    "Medieval Art, Architecture & Literature — full revision"
  ]},
  artCulture: { label:"Art & Culture", color:"#C77DAE", topics:[
    "Indian Architecture — Indus to Medieval (temples, forts, mosques)",
    "Sculpture & Pottery traditions",
    "Indian Paintings — Mural & Miniature traditions",
    "Classical Dances of India",
    "Indian Music — Hindustani & Carnatic",
    "Indian Literature (Classical & Regional)",
    "Religion & Philosophy — Schools of Indian philosophy",
    "Fairs, Festivals & Crafts of India",
    "UNESCO World Heritage Sites in India, Awards & Honours",
    "Full revision of Art & Culture"
  ]},
  scienceTech: { label:"Science & Technology", color:"#4A90B5", topics:[
    "Physics basics relevant to UPSC (mechanics, units)",
    "Space Technology — ISRO missions, satellites",
    "Nuclear Technology, Defence Technology (missiles, DRDO)",
    "Biotechnology basics, GM crops",
    "Health & Medicine — diseases, vaccines",
    "IT & Computers — basics, cyber security",
    "Emerging Technology — AI, Robotics, Blockchain",
    "Nanotechnology, Materials Science",
    "Environment-related tech, Renewable energy tech",
    "Chemistry basics relevant to UPSC (everyday chemistry, chemicals in news)",
    "Biology basics — Human body systems, diseases",
    "Agricultural technology, Genetics",
    "Miscellaneous — awards in S&T, government schemes for S&T",
    "Current S&T developments compilation",
    "Full revision of Science & Technology"
  ]},
  environment: { label:"Environment & Ecology", color:"#5FA85B", topics:[
    "Ecology basics — ecosystem, food chain, biomes",
    "Biodiversity — types, hotspots, conservation",
    "Protected Areas — National Parks, Wildlife Sanctuaries, Biosphere Reserves",
    "Environmental Pollution — Air, Water, Soil",
    "Climate Change — basics, IPCC, Paris Agreement",
    "International Conventions & Protocols (CBD, CITES, Ramsar, Montreal Protocol)",
    "National Environmental Policies & Acts (Environment Protection Act, Wildlife Protection Act, Forest Acts)",
    "Environmental Organizations — UNEP and national bodies",
    "Renewable Energy & Sustainable Development",
    "Disaster Management basics",
    "Species in news, Invasive species, Environmental current affairs",
    "Full revision of Environment & Ecology"
  ]},
  ethics: { label:"Ethics (GS Paper 4)", color:"#D9B44A", topics:[
    "Ethics basics — definitions, human values, dimensions",
    "Determinants & consequences of ethics, ethics in private/public relations",
    "Attitude — content, structure, function, influence",
    "Aptitude & foundational values for civil service",
    "Emotional Intelligence — concepts, utility",
    "Moral Thinkers & Philosophers — Indian & Western",
    "Public/Civil Service Values, ethics in public administration",
    "Probity in Governance — concept, philosophical basis",
    "Information sharing, transparency, accountability",
    "Work culture, quality of service delivery",
    "Challenges of corruption, ethical issues in international relations/funding",
    "Case studies practice — full revision of Ethics"
  ]},
  essay: { label:"Essay", color:"#9C7FC9", topics:[
    "Essay writing basics — structure, approach",
    "Philosophical / abstract essay practice",
    "Social issues essay practice",
    "Economic / development essay practice",
    "Political / governance essay practice",
    "Essay revision — review past essays, refine style"
  ]},
  csat: { label:"CSAT", color:"#5B8FC9", topics:[
    "Comprehension basics",
    "Comprehension practice sets",
    "Logical Reasoning — basics",
    "Logical Reasoning — practice sets",
    "Analytical Reasoning",
    "Decision Making",
    "Basic Numeracy — Number system",
    "Basic Numeracy — Percentage, Ratio, Averages",
    "Basic Numeracy — Time & Work, Time-Speed-Distance",
    "Data Interpretation basics",
    "Data Interpretation practice",
    "Probability & Permutation-Combination basics",
    "Mixed practice test 1",
    "Mixed practice test 2",
    "Full CSAT revision + strategy"
  ]},
  currentAffairs: { label:"Current Affairs Consolidation", color:"#C97F4A", topics:[
    "Current Affairs — Polity & Governance (last 6 months) compilation",
    "Current Affairs — Economy (last 6 months) compilation",
    "Current Affairs — International Relations (last 6 months) compilation",
    "Current Affairs — Environment & Ecology (last 6 months) compilation",
    "Current Affairs — Science & Technology (last 6 months) compilation",
    "Current Affairs — Schemes, Reports & Indices, Committees compilation",
    "Current Affairs — Awards, Places in news, Miscellaneous compilation",
    "Current Affairs — Full compilation revision + quiz"
  ]},
  revision1: { label:"Revision Round 1", color:"#8FA85B", topics:[
    "Polity revision — Constitutional Framework + Fundamental Rights/DPSP",
    "Polity revision — Union & State Executive, Legislature, Judiciary",
    "Polity revision — Federalism, Constitutional Bodies, Local Government + MCQ practice",
    "Geography revision — Physical Geography (Geomorphology, Climatology, Oceanography)",
    "Geography revision — Indian Geography (Physiography, Drainage, Climate, Vegetation) + map practice",
    "Economy revision — National Income, Money & Banking, Inflation, Public Finance",
    "Economy revision — External Sector, Agriculture, Industry, Employment + MCQ practice",
    "Modern History revision — 1757 to 1857 (British expansion, Revolt of 1857)",
    "Modern History revision — 1857 to 1947 (Nationalist Movement phases)",
    "Ancient History revision — Indus Valley to Gupta Age",
    "Medieval History revision — Delhi Sultanate to Mughal decline",
    "Art & Culture revision — Architecture, Painting, Music, Dance, Literature",
    "Science & Tech revision — Space, Defence, Biotech, IT",
    "Science & Tech revision — Health, Environment tech, emerging tech",
    "Environment & Ecology revision — Biodiversity, Protected Areas, Pollution, Climate Change",
    "Ethics (GS4) revision — core concepts, thinkers, case-study approach",
    "Current Affairs revision — last 6 months compilation",
    "Optional Paper 1 revision (PSIR / Malayalam)",
    "Optional Paper 2 revision (PSIR / Malayalam)",
    "Full mixed MCQ test (all subjects) + error analysis"
  ]},
  revision2: { label:"Revision Round 2", color:"#6FA893", topics:[
    "Polity — Previous Year Questions practice & analysis",
    "Polity — weak-area targeted revision based on Round 1 errors",
    "Geography — Previous Year Questions practice & map-based revision",
    "Geography — weak-area targeted revision",
    "Economy — Previous Year Questions practice & Economic Survey linkage",
    "Economy — weak-area targeted revision",
    "Modern History — Previous Year Questions practice",
    "Modern History — weak-area targeted revision",
    "Ancient & Medieval History — Previous Year Questions practice",
    "Art & Culture — Previous Year Questions practice",
    "Science & Tech — Previous Year Questions practice",
    "Environment — Previous Year Questions practice",
    "Ethics — case-study practice (10 case studies)",
    "Essay — practice writing 2 full essays + review",
    "Current Affairs — last 12 months compilation revision",
    "Optional Paper 1 — PYQ practice & weak-area revision",
    "Optional Paper 2 — PYQ practice & weak-area revision",
    "CSAT — full-length practice + strategy refinement",
    "Full syllabus flash-card revision — Day 1",
    "Full syllabus flash-card revision — Day 2 + full mixed mock test"
  ]},
  testSeries: { label:"Test Series", color:"#E4573D", topics:[
    "Prelims Full-Length Mock Test 1 + detailed analysis",
    "Mains GS Paper 1 Mock + review",
    "Mains GS Paper 2 Mock + review",
    "Prelims Full-Length Mock Test 2 + detailed analysis",
    "Mains GS Paper 3 Mock + review",
    "Mains GS Paper 4 (Ethics) Mock + review",
    "Optional Paper 1 Mock + review",
    "Prelims Full-Length Mock Test 3 + detailed analysis",
    "Optional Paper 2 Mock + review",
    "Essay Mock (2 essays) + review",
    "Mains GS Paper 1 Mock 2 + review",
    "Prelims Full-Length Mock Test 4 + detailed analysis",
    "Mains GS Paper 2 Mock 2 + review",
    "Mains GS Paper 3 Mock 2 + review",
    "Optional Paper 1 Mock 2 + review",
    "Prelims Full-Length Mock Test 5 + detailed analysis",
    "Optional Paper 2 Mock 2 + review",
    "Mains GS Paper 4 Mock 2 + review",
    "Essay Mock 2 + review",
    "Prelims Full-Length Mock Test 6 (Final) + detailed analysis",
    "Full Mains Test simulation — all GS papers back-to-back — Day 1",
    "Full Mains Test simulation — Optional papers back-to-back — Day 2",
    "Final strategy review — exam-day plan, revision index check, rest"
  ]}
};

export const CORE_ORDER_DEFAULT = ["ethics","polity","geography","economy","modernHistory","ancientHistory","medievalHistory",
  "artCulture","scienceTech","environment","essay","csat","currentAffairs"];
export const FIXED_TAIL = ["revision1","revision2","testSeries"]; /* always last — revision/test phases depend on content already covered */
export const SUBJECT_LABELS_CORE = CORE_ORDER_DEFAULT.map(k=>({key:k, label:SUBJECTS[k].label}));

export const PSIR_TOPICS = [
  "Political Theory — meaning, scope, approaches (traditional & behavioural)",
  "Theories of State — Liberal & Neo-liberal",
  "Theories of State — Marxist, Pluralist",
  "Theories of State — Post-colonial, Feminist",
  "Justice — conceptions: procedural & substantive",
  "Justice — Rawls's theory of justice",
  "Justice — critics of Rawls: Nozick, Communitarians",
  "Equality — social, political, economic equality",
  "Equality — relationship with freedom, affirmative action",
  "Rights — meaning, theories (natural, legal, positive)",
  "Rights — kinds of rights, concept of Human Rights",
  "Democracy — classical theories",
  "Democracy — contemporary theories & models (participatory, deliberative)",
  "Concept of Power — hegemony (Gramsci)",
  "Concept of Power — ideology, legitimacy",
  "Political Ideologies — Liberalism",
  "Political Ideologies — Socialism, Marxism",
  "Political Ideologies — Fascism",
  "Political Ideologies — Gandhism",
  "Political Ideologies — Feminism",
  "Indian Political Thought — Dharmashastra, Kautilya, Buddhist tradition",
  "Indian Political Thought — Sri Aurobindo, M.N. Roy",
  "Modern Indian Political Thought — Gandhi",
  "Modern Indian Political Thought — Ambedkar",
  "Modern Indian Political Thought — Nehru, Lohia",
  "Modern Indian Political Thought — Iqbal, Jinnah, Savarkar",
  "Western Political Thought — Plato",
  "Western Political Thought — Aristotle",
  "Western Political Thought — Machiavelli",
  "Western Political Thought — Hobbes",
  "Western Political Thought — Locke",
  "Western Political Thought — Rousseau",
  "Western Political Thought — Marx",
  "Western Political Thought — Gramsci, Hannah Arendt",
  "Indian Nationalism — strategies of freedom struggle, perspectives",
  "Making & Salient Features of the Indian Constitution",
  "Union & State Legislature-Executive relations",
  "Judiciary — review, activism; Federalism & Centre-State relations",
  "Planning & Economic Development; Party system, social cleavages",
  "Social Movements (women's, environmental, human rights) — Paper 1 full revision",
  "Comparative Politics — nature, major approaches",
  "State in comparative perspective — capitalist & socialist state",
  "State under globalization",
  "Political parties, pressure groups, social movements (comparative)",
  "Globalization — responses from developed & developing societies",
  "Approaches to IR — Idealist, Realist",
  "Approaches to IR — Marxist, Systems theory, Neo-realism/Neo-liberalism",
  "Key Concepts — national interest, security, power",
  "Key Concepts — balance of power, deterrence",
  "Changing International Political Order — rise & fall of superpowers",
  "Changing International Political Order — NAM, unipolarity, multipolarity",
  "Regionalisation — European Union",
  "Regionalisation — ASEAN, SAARC, APEC",
  "United Nations — main organs",
  "United Nations — specialized agencies, reform proposals",
  "Contemporary Concerns — Human rights in world politics",
  "Contemporary Concerns — Environment & global commons",
  "Contemporary Concerns — Gender justice",
  "Contemporary Concerns — Terrorism, nuclear proliferation",
  "Indian Foreign Policy — determinants, institutions of policy-making",
  "Panchsheel, Non-Alignment",
  "India's engagement with major powers post-Cold War",
  "India-Pakistan relations",
  "India-China relations",
  "India-Bangladesh, Nepal relations",
  "India-Sri Lanka, Myanmar relations",
  "India and SAARC, regional cooperation",
  "India and Africa, Latin America",
  "India and global centres of power — US, EU",
  "India, Japan, Russia, ASEAN",
  "India and the UN system, global forums (G20, BRICS)",
  "India's Nuclear policy, disarmament efforts",
  "Foreign policy issues — energy security, cyber security",
  "Foreign policy issues — diaspora, soft power",
  "PYQ practice — Paper 1: Political Theory",
  "PYQ practice — Paper 1: Indian Politics",
  "PYQ practice — Paper 2: Comparative Politics",
  "PYQ practice — Paper 2: International Relations",
  "Answer-writing practice — mixed PSIR questions",
  "Full PSIR revision (Paper 1 + Paper 2) + mock test"
];

export const MALAYALAM_TOPICS = [
  "Dravidian language family & Malayalam's place in it",
  "Origin theories of the Malayalam language",
  "Evolution stages — Pazhamalayalam (Old Malayalam) inscriptions",
  "Pattu tradition — Ramacharitam and early Pattu works",
  "Pattu tradition (contd.) — Krishnagatha, Niranam poets",
  "Manipravalam tradition — origin, Champu Kavyas",
  "Manipravalam (contd.) — Unniyachi Charitam, Unnuneeli Sandesam",
  "Folk literature (Naadan Pattukal) — Vadakkan Pattukal, Thekkan Pattukal",
  "Arabi-Malayalam literature",
  "Bhakti movement's impact — Cherusseri's Krishnagatha",
  "Ezhuthachan — Adhyatma Ramayanam, Mahabharatam",
  "Post-Ezhuthachan period — Kunchan Nambiar & Thullal literature",
  "Venmani poets & the transition to modern poetry",
  "Contact with the West — missionary contribution, growth of prose",
  "Development of Malayalam prose — early novels",
  "Development of Malayalam grammar & lexicon works",
  "Modern poetry — the Romantic trio: Asan, Ulloor, Vallathol (overview)",
  "Development of Malayalam drama",
  "Development of Malayalam short story",
  "Development of Malayalam novel — the realism period",
  "Progressive Literary Movement (Purogamana Sahitya movement)",
  "Modernism (Adhunikatha) in Malayalam literature",
  "Post-modern trends in Malayalam literature",
  "Malayalam literary criticism — traditional criticism",
  "Malayalam literary criticism — modern schools",
  "Contribution of Christian missionaries to Malayalam prose",
  "Contribution of print & journalism to literature's growth",
  "Regional dialects & their literary reflection",
  "Malayalam literature and social reform movements",
  "Women writers in Malayalam literature — historical overview",
  "Dalit literature in Malayalam",
  "Literature of the Malayalam diaspora",
  "Translation literature — major translated works",
  "Children's literature in Malayalam",
  "Malayalam cinema and literature — interconnections",
  "Sahitya Akademi & Jnanpith awardees — overview",
  "Major literary movements — timeline consolidation",
  "Comparative study — influence of Sanskrit/Tamil on Malayalam",
  "PYQ practice — Paper 1: History of Language & Literature",
  "Full Paper 1 revision",
  "Poetry — Kumaran Asan: Veena Poovu, Chinthavishtayaya Sita",
  "Poetry — Vallathol: selected works",
  "Poetry — Ulloor: selected works",
  "Poetry — G Sankara Kurup: selected works",
  "Poetry — Changampuzha: Ramanan and other works",
  "Poetry — Vailoppilli Sreedhara Menon: selected works",
  "Poetry — ONV Kurup, Akkitham: selected works",
  "Poetry — modern & contemporary poets (overview)",
  "Novel — O Chandu Menon: Indulekha",
  "Novel — Thakazhi Sivasankara Pillai: Chemmeen",
  "Novel — O V Vijayan: Khasakkinte Itihasam",
  "Novel — M T Vasudevan Nair: selected works",
  "Novel — S K Pottekkatt: selected works",
  "Novel — other major novelists (overview)",
  "Short story — Vaikom Muhammad Basheer: selected works",
  "Short story — Lalithambika Antharjanam, Kamala Suraiya: selected works",
  "Short story — T Padmanabhan and contemporaries",
  "Drama — C J Thomas, N Krishna Pillai: selected works",
  "Drama — contemporary Malayalam drama (overview)",
  "Literary Criticism — Kuttikrishna Marar: selected essays",
  "Literary Criticism — Kesari Balakrishna Pillai and modern critics",
  "Literary Criticism — contemporary critical theory in Malayalam",
  "Biography & autobiography in Malayalam literature",
  "Travelogue writing in Malayalam",
  "Essay tradition in Malayalam",
  "Text analysis practice — poetry selections",
  "Text analysis practice — novel selections",
  "Text analysis practice — short story selections",
  "Text analysis practice — drama & criticism selections",
  "Comparative analysis across genres",
  "PYQ practice — Paper 2: poetry & prose",
  "PYQ practice — Paper 2: criticism & unseen passages",
  "Précis / translation practice (Malayalam-English)",
  "Answer-writing practice — mixed Paper 2 questions",
  "Revision — poetry texts",
  "Revision — prose texts (novel & short story)",
  "Revision — drama & criticism",
  "Full Paper 2 revision",
  "Full syllabus mock test (Paper 1 + Paper 2)",
  "Final consolidated revision"
];

export const FINAL_PHASE_CYCLE = [
  "Integrated Revision: Polity — full re-read of notes + 20 MCQs",
  "Integrated Revision: Geography — full re-read of notes + map practice",
  "Integrated Revision: Economy — full re-read of notes + 20 MCQs",
  "Integrated Revision: Modern History — full re-read of notes + 20 MCQs",
  "Integrated Revision: Ancient & Medieval History — full re-read of notes",
  "Integrated Revision: Art & Culture + Environment — full re-read of notes",
  "Integrated Revision: Science & Tech + CSAT practice set",
  "Integrated Revision: Ethics — case studies + Essay outline practice",
  "Integrated Revision: Optional Paper 1 — full re-read of notes",
  "Integrated Revision: Optional Paper 2 — full re-read of notes",
  "Prelims Full-Length Mock + detailed analysis",
  "Mains GS Paper 1 + Paper 2 Mock (back-to-back) + review",
  "Mains GS Paper 3 + Paper 4 Mock (back-to-back) + review",
  "Optional Paper 1 Full Mock + review",
  "Optional Paper 2 Full Mock + review",
  "Current Affairs — last 3 months rapid revision",
  "Essay writing — 2 full essays under timed conditions",
  "Weak-area revision (based on this cycle's mock errors)",
  "Full syllabus flash-card / one-pager revision",
  "Rest & light revision — revisit only flagged/starred topics"
];

/* Flatten GS days 1-220, then append the fixed final integrated phase (221-300) */
export let GS_DAYS = [];
export function rebuildGSDays(coreOrder){
  GS_DAYS = [];
  coreOrder.concat(FIXED_TAIL).forEach(key=>{
    const subj = SUBJECTS[key];
    subj.topics.forEach((topic, idx)=>{
      GS_DAYS.push({
        day: GS_DAYS.length+1,
        subjectKey:key,
        subjectLabel: subj.label,
        color: subj.color,
        topic: topic,
        posInSubject: idx+1,
        subjectTotal: subj.topics.length
      });
    });
  });
  for(let c=0;c<4;c++){
    for(let i=0;i<20;i++){
      const day = GS_DAYS.length+1;
      let topic = FINAL_PHASE_CYCLE[i];
      if(c>0) topic += " — Round " + (c+1);
      GS_DAYS.push({
        day, subjectKey:"finalPhase", subjectLabel:"Final Integrated Phase", color:"#C9A227",
        topic, posInSubject: c*20+i+1, subjectTotal:80
      });
    }
  }
}
rebuildGSDays(CORE_ORDER_DEFAULT);

export const TOTAL_DAYS = 300;
export const OPTIONAL_DAYS = 80;

/* Daily current-affairs theme rotation — a habit slot every single day, distinct from the
   periodic "Current Affairs Consolidation" phase which revises what's been noted here. */
export const CA_THEMES = ["Polity & Governance","Economy","International Relations","Environment & Ecology",
  "Science & Technology","Schemes, Reports & Indices","Miscellaneous / Art & Culture / Social Issues"];
export function caTopicForDay(day){
  const theme = CA_THEMES[(day-1) % CA_THEMES.length];
  return "Read today's newspaper/CA source with a lens on " + theme + ". Note 3–5 Prelims/Mains-worthy points.";
}

